image: Visual Studio 2017
configuration:
  - Release
  - Debug
cache:
  - C:\Program Files\NASM\
  # Cache Nuget packages in "packages" folder. Break cache if "packages.config" is updated.
  - packages -> **\packages.config
install:
  - if not exist "%ProgramFiles%\NASM\"  choco install -y nasm
  - set PATH=%ProgramFiles%\NASM;%PATH%
  - nasm -v
before_build: nuget restore
build:
  project: OP2Internal.sln
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\test
  - '%APPVEYOR_BUILD_FOLDER%\%PLATFORM%\%CONFIGURATION%\Test.exe'
  - cd %APPVEYOR_BUILD_FOLDER%
