image: Visual Studio 2017
configuration:
  - Release
  - Debug
cache:
  - C:\Program Files\NASM\
install:
  - if not exist "%ProgramFiles%\NASM\"  choco install -y nasm
  - set PATH=%ProgramFiles%\NASM;%PATH%
  - nasm -v
build:
  project: OP2Internal.sln
